
import 'package:restaurants/stateNameList.dart';

final dummyState = [
  StateNameList("Abia","assets/image/IMG_8504.jpg"),
  StateNameList("Adamawa","assets/image/IMG_8504.jpg"),
  StateNameList("Akwa Ibom","assets/image/IMG_8504.jpg"),
  StateNameList("Anambra","assets/image/IMG_8504.jpg"),
  StateNameList("Bauchi","assets/image/IMG_8504.jpg"),
  StateNameList("Bayelsa","assets/image/IMG_8504.jpg"),
  StateNameList("Benue","assets/image/IMG_8504.jpg"),
  StateNameList("Borno","assets/image/IMG_8504.jpg"),
  StateNameList("Cross RIver","assets/image/IMG_8504.jpg"),
  StateNameList("Delta","assets/image/IMG_8504.jpg"),
  StateNameList("Ebonyi","assets/image/IMG_8504.jpg"),
  StateNameList("Edo","assets/image/IMG_8504.jpg"),
  StateNameList("Ekiti","assets/image/IMG_8504.jpg"),
  StateNameList("Enugu","assets/image/IMG_8504.jpg"),
  StateNameList("Abuja","assets/image/IMG_8504.jpg"),
  StateNameList("Gombe","assets/image/IMG_8504.jpg"),
  StateNameList("Imo","assets/image/IMG_8504.jpg"),
  StateNameList("Jigawa","assets/image/IMG_8504.jpg"),
  StateNameList("Kaduna","assets/image/IMG_8504.jpg"),
  StateNameList("Kano","assets/image/IMG_8504.jpg"),
  StateNameList("Katsina","assets/image/IMG_8504.jpg"),
  StateNameList("Kebbi","assets/image/IMG_8504.jpg"),
  StateNameList("Kogi","assets/image/IMG_8504.jpg"),
  StateNameList("Kwara","assets/image/IMG_8504.jpg"),
  StateNameList("Lagos","assets/image/IMG_8504.jpg"),
  StateNameList("Nassarawa","assets/image/IMG_8504.jpg"),
  StateNameList("Niger","assets/image/IMG_8504.jpg"),
  StateNameList("Ogun","assets/image/IMG_8504.jpg"),
  StateNameList("Ondo","assets/image/IMG_8504.jpg"),
  StateNameList("Osun","assets/image/IMG_8504.jpg"),
  StateNameList("Oyo","assets/image/IMG_8504.jpg"),
  StateNameList("Plateau","assets/image/IMG_8504.jpg"),
  StateNameList("Rivers","assets/image/IMG_8504.jpg"),
  StateNameList("Sokoto","assets/image/IMG_8504.jpg"),
  StateNameList("Taraba","assets/image/IMG_8504.jpg"),
  StateNameList("Yobe","assets/image/IMG_8504.jpg"),
  StateNameList("Zamfara","assets/image/IMG_8504.jpg"),
  StateNameList("Abuja","assets/image/IMG_8504.jpg"),
];